### ISSUE TITLE
Make behaviors be defined by external scripts

### ISSUE THREAD

**Issue by zachrammell** [digipen-team-uwu/uwu-engine#14]
Behavior code is currently very messy and hard to maintain, we should implement a scripting engine and use interpreted scripts to simplify this process.
Candidates include Python, AngelScript, and others. If you would like to use a particular scripting language, please provide a recommendation.

**Comment by HardGaming01** [comment]
Also make behaviors exclusive from types. Currently a behaviors can only be made when there's a corresponding type.
Also I'm definitely not responding in a class

**Comment by zachrammell** [comment]
Yeah, ideally the engine shouldn't know anything about the game, it should just open asset and behavior files, make data from those things, transform the data, and run the behavior code that edits the data

**Comment by zachrammell** [comment]
this is a cancelled feature at the moment
