### ISSUE TITLE
Integrate testing framework

### ISSUE THREAD

**Issue by zachrammell** [digipen-team-uwu/uwu-engine#18]
We should integrate a unit testing framework in order to effectively ensure code correctness. If we test code before it even gets run in the engine, we will have far fewer implementation-based bugs.
Candidates for a unit testing framework include:
* Catch
https://github.com/catchorg/Catch2
* Google Test
https://github.com/google/googletest

If you have an opinion please comment, otherwise I will choose and integrate it myself.

**Comment by HardGaming01** [comment]
https://cliutils.gitlab.io/modern-cmake/chapters/testing.html
CMake integrated unit testing is also an valid options for unit tests.
Even though I've never used it by myself ive heard upper classmans recommending it.

**Comment by zachrammell** [comment]
CMake testing looks good, but it also looks like it's mainly for running the tests and requires a framework still. It would be great to have a framework and then run the tests via CMake.

**Comment by zachrammell** [comment]
catch2 was integrated
